### ISSUE TITLE
버그 모음집

### ISSUE THREAD

**Issue by koreatlwls** [boostcampwm-2022/android10-PlzStop#76]
- [x] 알람이 울릴 때 우리앱을 사용중이라면 알람 start화면으로 이동안함

**Comment by DoTheBestMayB** [comment]
- [x] 해결 여부

PlaceSearchFragment에 진입했을 때, 검색어가 입력되지 않아도 T MAP POIS를 호출 하는 것 같아요

![image](https://user-images.githubusercontent.com/48354989/206339038-6b072581-3c6a-4adc-9127-7e720b4f0aa7.png)

**Comment by jeeminimini** [comment]
- [ ] 간혹 알람 소리가 안들릴 때가 있음 -> 이럴경우 notification 클릭해도 알람시작 화면 안뜸

**Comment by jeeminimini** [comment]
- [ ] 알람 데이터에 null이 올때가 있음 -> 알람 시작 화면에 데이터 안뜨고, 이경우 미션 시작하면 앱 터짐

**Comment by DoTheBestMayB** [comment]
- [x] Navigation Component의 Bacstack을 이용해서 Fragment를 복원할 때, NavGraph가 다른 구간을 GlobalAction으로 이동하는 과정이 있던 경우, 앱이 터진다.

해당 문제 재현 방법
1. 분할 화면으로 앱 열기
2. 앱을 백그라운드에 둔 후 어느정도 시간이 지나서 앱을 다시 키기
3. IDE에서 Apply Changed 버튼을 눌러서 Fragment 다시 그리기

**Comment by koreatlwls** [comment]
![image](https://user-images.githubusercontent.com/61337202/206494868-dbe5927a-9763-43d4-bd54-bd49f34c6466.png)

- [x] 해결

심야버스는 데이터 안줘서 터짐

**Comment by jeeminimini** [comment]
- [ ] 막차시간이 없는 경우(평촌동행정복지센터 밑에 시간 안나옴) 알람 설정을 클릭하면 앱 터짐 -> 알람 설정 탭으로 들어갈 수 없도록 막아야할듯
<img src="https://user-images.githubusercontent.com/74500793/206627828-21d6eb24-2837-4b1f-871e-6620c5ad0d39.png" width="250" height="500"/>
여기 ui도 margin설정해줘야할듯요

**Comment by jeeminimini** [comment]
- [ ] 알람 등록은 되는데 바텀시트에 알람이 안뜨는 경우 -> 노티로 들어가면 데이터가 없다. (근데 알람 등록할때는 데이터 있던데..?)
<img src="https://user-images.githubusercontent.com/74500793/206649873-52054192-0cc4-4d39-a724-cdb774c141ef.png" width="250" height="500"/>

**Comment by DoTheBestMayB** [comment]
> * [ ]  알람 등록은 되는데 바텀시트에 알람이 안뜨는 경우 -> 노티로 들어가면 데이터가 없다. (근데 알람 등록할때는 데이터 있던데..?)
> 
> <img alt="" width="250" height="500" src="https://user-images.githubusercontent.com/74500793/206649873-52054192-0cc4-4d39-a724-cdb774c141ef.png">

activity viewModels를 모두 지우면서, 당시에는 괜찮아서 넘어갔는데, 문제가 발생하네요.

제가 수정할게요

**Comment by DoTheBestMayB** [comment]
근데 activity viewModels 문제는 아닐 수도 있어서(mapFragment에서 다시 생성하기 때문에)
알람 설정 부분 문제인지 확인해주세요

**Comment by DoTheBestMayB** [comment]
- [ ] 해결 여부

상세 경로 화면에서 길게 클릭 한 상태에서 드래그하면 지도가 이동되지 않음
상세 경로 화면에서 T MAP 지도에서 LongClickListener 혹은 TouchListener 설정

**Comment by DoTheBestMayB** [comment]
- [ ] 해결 여부

MapFragment에서 출발지, 도착지 버튼을 눌렀을 때, 다른 Fragment로 이동하기 전에 해당 패널 지우고 넘어가기

![image](https://user-images.githubusercontent.com/48354989/206836150-608bb1d7-156f-4f84-9243-efe753eed0f6.png)

**Comment by DoTheBestMayB** [comment]
- [ ] 해결 여부
경로 검색 화면 버그: 1784 검색 시 검색 결과가 없다고 나온다.
```
W/System.err: java.lang.IllegalStateException: Already resumed, but proposed with update Unexpected(exception=java.lang.Throwable: 요청에 성공했지만 body가 비어있습니다.)
W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:482)
W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:447)
W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
W/System.err:     at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
W/System.err:     at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:50)
W/System.err:     at com.stop.data.remote.ResultCall$enqueue$1.onResponse(ResultCall.kt:34)
W/System.err:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err:     at java.lang.Thread.run(Thread.java:1012)
E/PLACE_SEARCH_FRAGMENT: No Content Error
```
![Screenshot_20221213_155724_Plz Stop](https://user-images.githubusercontent.com/48354989/207247848-22359e3f-6669-48d7-afd2-d7b6cb17b828.png)

**Comment by DoTheBestMayB** [comment]
- [ ] 해결 여부
간혹 현재 위치 버튼을 눌러도 기본 위치로 설정해 둔 서울역으로 나옴
![Screenshot_20221213_160948_Plz Stop](https://user-images.githubusercontent.com/48354989/207251097-aca27f7b-9b81-42d2-995f-806f25b29b86.png)

**Comment by DoTheBestMayB** [comment]
- [ ] 해결 여부

삼성IT밸리 -> NAVER1784 검색 후, 7호선 - 신분당선 - 720-1 경로 클릭 시 발생
API 검색 결과가 없는 경우 `알 수 없는 오류`라고 나오는데, 다른 문구로 변경하기
http://apis.data.go.kr/6410000/busstationservice/getBusStationViaRouteList?stationId=219001102&serviceKey=
![알 수 없는 오류](https://user-images.githubusercontent.com/48354989/207499079-6b842988-ff38-4760-b2f6-e239d047d725.png)

**Comment by koreatlwls** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/61337202/208042192-eaa1a3de-f840-4fcf-b98f-36f71e81cbc0.png">

- [ ] 해결여부

처음에 걷는 경로가 없어서 walk route로 캐스팅 실패
